"""
This type stub file was generated by pyright.
"""

from typing import Protocol

from .models import MappedFrame as MappedFrame

"""
This type stub file was generated by pyright.
"""

def split_host_port(host: str, port: int | None = ...) -> tuple[str, int | None]: ...

class IRegulApiInterface(Protocol):
    async def get_data(self) -> MappedFrame | None: ...
    async def defrost(self) -> bool: ...
    async def check_auth(self) -> bool: ...
